### ISSUE TITLE
group_by task always reports 'changes'

### ISSUE THREAD

**Issue by OndrejHome** [OndrejHome/ansible.ha-cluster-pacemaker#11]
**Issue:**
Since the inclusion of code that required `group_by`, the role always reports the task with `group_by` to be `changed`. Even when `changed_when: False` is used. This issue is here as reminder to check how (and if) this can be somehow fixed.
This seems to be limited to newer versions of Ansible (2.9.x/2.10.x), version 2.8.x has no such issue.

**For possible contributors:** 
If you have a good idea on how to fix this issue feel free to open PR and refer to this issue.

**Comment by mashpie** [comment]
as a feedback from locally testing fixes: `changed_when: false` perfectly works for me and ansible 2.13.x

```yaml
- name: Add a group to the inventory for remote nodes
  changed_when: false
  group_by:
    key: "cluster{{ rand_id }}_node_is_remote_{{ cluster_node_is_remote | bool }}"
```
