### ISSUE TITLE
how to enable resource from playbook

### ISSUE THREAD

**Issue by mashpie** [OndrejHome/ansible.ha-cluster-pacemaker#24]
Hey @OndrejHome,

looke like you built the best corosync/pacemaker role available. Trying out to steup a simple 2-node cluster with a shared IP for failover.

But I can't enable that resource. So I feel to be missing something form docs. Role + vars is setup as so:

```yaml
    - role: ondrejhome.ha-cluster-pacemaker
      tags: cluster
      cluster_name: "mailx-cluster"
      cluster_user_pass: ngzj27rgr4k7
      cluster_firewall: false
      cluster_configure_fence_xvm: false
      cluster_resource:
        - name: "sharedIP-213"
          state: present
          resource_type: "ocf:heartbeat:IPaddr2"
          options: "ip=xxx.yyy.zzz.213 cidr_netmask=24 op monitor interval=10s"
```

`crm_mon` gives:

```
Cluster Summary:
  * Stack: corosync
  * Current DC: mailx-06 (version 2.0.5-ba59be7122) - partition with quorum
  * Last updated: Wed Nov 23 19:25:43 2022
  * Last change:  Wed Nov 23 19:18:44 2022 by root via cibadmin on mailx-05
  * 2 nodes configured
  * 1 resource instance configured

Node List:
  * Online: [ mailx-05 mailx-06 ]

Active Resources:
  * No active resources
```

while `pcs resource config` knows that resource properly:

```
 Resource: sharedIP-213 (class=ocf provider=heartbeat type=IPaddr2)
  Attributes: cidr_netmask=24 ip=xxx.yyy.zzz.213
  Operations: monitor interval=10s (sharedIP-213-monitor-interval-10s)
              start interval=0s timeout=20s (sharedIP-213-start-interval-0s)
              stop interval=0s timeout=20s (sharedIP-213-stop-interval-0s)
```

and even after `pcs resource enable sharedIP-213` that resource remains "inactive"

Any hints? What am I missing?

---

Ah btw: firewall is shut down on local dev
