### ISSUE TITLE
"validate redundant ring ip" false positive without default gateway

### ISSUE THREAD

**Issue by Obihoernchen** [OndrejHome/ansible.ha-cluster-pacemaker#31]
# Issue

The following check can fail if there is no default gateway configured on cluster nodes.

https://github.com/OndrejHome/ansible.ha-cluster-pacemaker/blob/master/tasks/main.yml#L144-L150
```yaml
- name: validate redundant ring ip
  fail:
    msg: >-
      invalid redundant ip {{ rrp_ip }} for {{ ansible_hostname }}:
      must be different than default ip {{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}
  when: rrp_ip is defined and rrp_ip == ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0])
  any_errors_fatal: true
```

Without a default gatway `ansible_default_ipv4.address` is not set, therefore the check falls back to `default(ansible_all_ipv4_addresses[0])` but this fallback can cause issues because it resolves to wrong IP addresses.

# Example

Let me explain this with an example:

A host (`home02`) has no default gateway configured and 3 network interfaces (`bond[0-2]`)

```
[root@home02 ~]# ip r
10.10.0.0/16 dev bond0 proto kernel scope link src 10.10.200.2 metric 302 
10.12.0.0/16 dev bond1 proto kernel scope link src 10.12.200.2 metric 301 linkdown 
192.168.1.0/30 dev bond2 proto kernel scope link src 192.168.1.2 metric 300 
[root@home02 ~]# hostname -I
192.168.1.2 10.12.200.2 10.10.200.2 
```

Therefore, Ansible detects the following facts:

```json
"ansible_all_ipv4_addresses": [
    "192.168.1.2",
    "10.10.200.2",
    "10.12.200.2"
],
"ansible_default_ipv4": {},
```

The hostname `home02` resolves to `10.10.200.2`.
```
[root@home02 ~]# hostname -i
10.10.200.2
[root@home02 ~]# ping -c1 home02
PING home02.service (10.10.200.2) 56(84) bytes of data.
64 bytes from home02.service (10.10.200.2): icmp_seq=1 ttl=64 time=0.009 ms
```

The host should be configured with ring0 on bond0 and ring1 on bond2.

```conf
node {
    ring0_addr: home02
    ring1_addr: 192.168.1.2
    name: home02
    nodeid: 2
}
```

Unfortunately, this is not possible because `default(ansible_all_ipv4_addresses[0])` is `192.168.1.2` which is incorrect, because `home02` resolves to `10.10.200.2`, not `192.168.1.2`. It should be `10.10.200.2`.

Therefore, setting `rrp_interface=bond2` for `home02` fails with:

```
fatal: [home02]: FAILED! => changed=false 
  msg: 'invalid redundant ip 192.168.1.2 for home02: must be different than default ip 192.168.1.2'
```

# Proposal

I see multiple options:

1. Replace the fallback check `default(ansible_all_ipv4_addresses[0])`  with an actual hostname lookup
2. Remove the fallback and skip the check if `ansible_default_ipv4` is unset
3. Allow to configure an IP address for `ring0_addr`, too
