### ISSUE TITLE
Setup firewall task conditional always true on CentOS

### ISSUE THREAD

**Issue by oebeledrijfhout** [OndrejHome/ansible.ha-cluster-pacemaker#8]
instead of this:

```
- name: Setup firewall for RHEL/CentOS systems
  include_tasks: "firewall-el{{ ansible_distribution_major_version }}.yml"
  when: cluster_firewall|bool and ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
```


it should look like this:

```
- name: Setup firewall for RHEL/CentOS systems
  include_tasks: "firewall-el{{ ansible_distribution_major_version }}.yml"
  when:                                                                                                                                                                                                                                          
    - cluster_firewall|bool
    - ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
```
